test/test_julia.jl

Termination of the model was moved to `finalize_test.jl`, but this was forgotten.

Remove finalize from test_julia.jl

---

interface_script/build_interface.py
src/CUTEst.jl
src/core_interface.jl
test/build_test.jl
test/runtests.jl
test/test_core.jl
test/test_julia.jl

This bundle contains
- The script to generate, and the generated, core interface
- Tests for a large part of the core interface
- Change in `CUTEst.jl` to use the core interface instead of the `ccall`.
Some constrained functions were not tested, specially the finite element related.
Most unconstrained functions were not tested, as they were not going to improve coverage.

Core interface

---

src/julia_interface.jl

The documentation is converted to Markdown, ignore the line length but not the leading spaces. This could cause multiple spaces between words.

Remove troublesome spaces on documentation

---

.travis.yml
interface_script/build_interface.py
src/CUTEst.jl
src/core_interface.jl
src/documentation.jl
src/julia_interface.jl
src/specialized_interface.jl
test/finalize_test.jl
test/runtests.jl
test/runtests_unc.jl
test/test_core.jl
test/test_specialized.jl
travisCI/setup_travis_linux.sh

This allows opening one problem **after the other** without breaking.
Unfortunately, this prohibits the possibility of opening two problems **at the same time**.
Closes #4.
The most important changes are in `src/CUTEst.jl`. The libname or cutest_lib arguments are removed in favor of using a global variable.
Tested running **both** HS32 and HS4 verifying the values and by getting the objective function of **all** the CUTEst problems with the three interfaces (see `test/runtests.jl`).
The fix for travis (which allows failures of osx) is in a different commit.

Fix issue4

---

.gitignore
.travis.yml
REQUIRE
deps/build.jl
src/CUTEst.jl
src/julia_interface.jl
test/runtests.jl
travisCI/setup_travis_linux.sh

Two major changes.
- bindeps: Install CUTEst locally automatically for use inside CUTEst.jl
- use NLPModels.jl: Last "basic" main package for NLPModels.jl (Along with JuMP, Ampl and Simple)

Bindeps and AbstractNLPModel

---

src/julia_interface.jl

Fix hess_coord when obj_weight is zero

---

src/classification.jl
test/test_select.jl

Formerly it did not accept ranges, e.g., `objtype=1:4`. This supports any `AbstractVector` type.

select: more flexible canonicalization of objtype/contype

---

.travis.yml
REQUIRE
deps/build.jl
docs/src/index.md

The latest build fails because of sudo ([discourse](https://discourse.julialang.org/t/installing-dependencies-error-sudo-no-tty-present-and-no-askpass-program-specified/778),
https://github.com/JuliaLang/BinDeps.jl/issues/199)), thwarting my plans of one-commands-install-all.
My current strategy is building `gsl-1.16` using BinDeps, and requiring the user to install `gfortran` separately.
The next steps are to make sure that `libgfortran` is visible, possibly inside `deps`.

Bindeps again

---

src/specialized_interface.jl

Don't allocate gradient-like structure for specialized functions unless required

---

src/CUTEst.jl
src/julia_interface.jl
test/test_julia.jl

I've made some changes to increase type stability, but it didn't improve the timing of the functions.
Not sure if I did something wrong here. The timings are [here](https://gist.github.com/abelsiqueira/613e4794339ab537266368bdc271b2b4).
Changes previous `cons` to `consjac` that returns the constraints and Jacobian, while the currenty `cons` only return the constraints, like `NLPModels`.

Make some changes for type stability.

---

.travis.yml
src/julia_interface.jl

I was testing `cholfact` with `hess`, and it didn't work because `hess` currently returns a `SparseMatrixCSC{Float64,Int32}`, and the `Int32` needs to be `Int64`. Changing only `hess` and not `hess_coord` should also work, what do you think?
Failing code:
```julia
Hx = Symmetric(hess(nlp, x), :L)
F = cholfact(Hx)
```

hess and jac indexes are in Int64

---

src/CUTEst.jl

On NLPModels.jl/nlp_types.jl, the definition of nnzj is
nnzj = max(0, min(nnzj, nvar * ncon))
For BA-L16, nvar * ncon overflows to a negative value, which sets
nnzj = 0.
Closes #139

Fix error when nvar * ncon > 32 bit int maximum

---

deps/build.jl

`brew upgrade` returns an error if the latest version of a formula is already installed. `Pkg.build("CUTEst")` fails if we don't catch that error.

catch brew upgrade error

---

src/classification.jl

This may just be my own preference, but I expected the array returned from CUTEst.select to be of type Array{String,1}

Return Array{String} from select

---

deps/build.jl

New linux-cutest-0.4.0 doesn't create a link to libgfortran, since
it is no longer necessary

Use linux-cutest-0.4.0

---

src/CUTEst.jl

The command `sifdecoder("LUBRIFC", "-show")` currently fails because it does not decode a problem, but we still try to compile `ELFUN.f`, etc. This change checks that a Fortran file is produced before trying to compile.

allow command that does not decode a problem

---

.travis.yml
Project.toml
docs/Project.toml
docs/src/tutorial.md

This is being compared against a branch `release-0.6`, with cherry-picked commits since `0.6.2`.

Limit version and prepare for release 0.6.3

---

.travis.yml
Project.toml
docs/Project.toml
docs/src/tutorial.md

Needs https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/167 and release.

Limit version, update docs and coverage to Julia 1.3, release 0.7.0

---

src/CUTEst.jl

This should allow auto-merging of releases. Currently they fail because `import CUTEst` fails (e.g. https://github.com/JuliaRegistries/General/pull/11199). And that fails because gfortran is not installed. With the new CUTEst_JLL, we pass the build phase, and thus can fail on `import CUTEst` without throwing errors.

Allow import CUTEst without gfortran

---

Artifacts.toml
Project.toml
src/CUTEst.jl
test/runtests.jl

Use Julia 1.3's artifact feature to download and install the SIF collection once and for all. According to the docs, the artifact will be shared by several installations of CUTEst.jl (say, in several environments), and so will be downloaded only once.

package SIF collection as artifact

---

src/classification.jl

Currently, the underscores are interpreted as begin/end italics, so it's not obvious that the keyword args have underscores.

fix docstring to prevent italics

---

Project.toml
docs/Project.toml
src/CUTEst.jl

CUTEst only works with Float64, so the struct is specialized.
I don't know if it works with GPU. If it does, I can change to `S`.

Update to NLPModels 0.15

---

src/CUTEst.jl
src/core_interface.jl
src/julia_interface.jl
test/runtests.jl
test/test_core.jl

Hey JSO devs, we've been using CUTEst.jl for benchmarking our solver [MadNLP.jl](https://github.com/sshin23/MadNLP.jl), and we recently found that JSO's current julia interface does not efficiently handle view inputs. Please consider merging this PR.
This PR adds better support for view inputs for CUTEst.jl's julia interface.
The current CUTEst.jl julia interface converts any `AbstractVector` input to `Vector{Float64}` to make it compatible with subsequent ccalls, and this process accompanies memory allocations. But when the AbstractVector is a stride-one array (which typically comes from a view of a `Vector` over a `UnitRange`), this can be avoided by directly passing it to C functions. 
I have added the definition for `StrideOneVector{T}`, and replaced the type specifications in the …

Add support for view inputs

---

src/CUTEst.jl
src/julia_interface.jl

This PR implements the changes suggested in #270.
To avoid memory allocation in `NLPModels.jac_coord!` and `NLPModels.obj`, a workspace array is added in `CUTEstModel`. The workspace array is used within `NLPModels.jac_coord!` and `NLPModels.obj` to avoid creating new arrays.
I believe no change in the test is necessary for this PR.

Fix for jac_coord! allocation issue

---

docs/make.jl

With this change, a new workflow named "documenter/deploy" appears in the list of checks when the docs have finished building.
Clicking on "details" takes you to the docs resulting from the pull request.

use push_preview = true in docs deploy

---

test/test_core.jl
test/test_julia.jl

Since https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/pull/50/files there nonlinear function in NLPModelsTest.jl and CUTEst.jl now differs. So, I suggest to test with the function (defined in this PR) `compare_cons`.
The unit tests then break because of the linear API, see https://github.com/JuliaSmoothOptimizers/CUTEst.jl/tree/add-linear-API (with NLPModelsTest 0.8.1), coming in a following PR

Fix unit tests for problem hs14

---

docs/Project.toml
src/CUTEst.jl

Add `lin_nnzj` and `nln_nnzj` in the meta.
There is no specific API to get the linear jacobian in CUTEst, so I used `nnzj` as an upper bound.
The tests break in this branch, the working one is here: https://github.com/JuliaSmoothOptimizers/CUTEst.jl/tree/add-linear-API

Add meta for linear API

---

Project.toml

and drop before 0.18 as the linear API wasn't implemented there.

Bump to NLPModels 0.19

---

src/julia_interface.jl

If x is already a Vector{Float64} and y = convert(Vector{Float64}, x),
then x == y and x === y, which isn't true if y = Vector{Float64}(x).

use convert instead of Vector(x)

---

src/julia_interface.jl

This allows to replace things like `hv[1:(nlp.meta.nvar)] .= hvc` by `hv .= hvc`

add `lencheck` everywhere

---

src/julia_interface.jl

Fixes #292 
updated julia_interface.jl

Added `increment!` and `decrement!` functions.

---

.github/workflows/ci.yml
.gitignore
Project.toml
README.md
docs/Project.toml
docs/make.jl
docs/src/index.md
docs/src/tutorial.md
src/CUTEst.jl

- Use the new JLL package dedicated to SIFDecode
- Use the latest SIF decoder implemented as a Fortran executable
- Support multiple precision for decoding (`:single`, `:double` and `:quadruple`)

Use the new package SIFDecode_jll.jl

---

.gitignore
gen/Project.toml
gen/README.md
gen/cutest.toml
gen/wrapper.jl
src/CUTEst.jl
src/libcutest.jl

- Generate Julia wrappers for single and double precision of CUTEst

Generate Julia wrappers with Clang.jl

---

.github/workflows/ci.yml
src/CUTEst.jl
src/sifdecoder.jl
test/runtests.jl

close #335 
- Add a new file `sifdecoder.jl`
- Split the previous function `sifdecoder` into two new functions `sifdecoder` and `build_libsif`
- Add CI on Windows
- Test the new function `sifdecoder` on all platforms
- Add an option `libsif_folder` to specify where we want to decode the SIF problems and build the shared libraries

Add a standalone sifdecoder function

---

gen/cutest.toml
gen/wrapper.jl
src/libcutest.jl

- Update `gen/wrappers.jl` to generate Julia wrappers that use pointers to routines in a shared library.

Use the Julia wrappers in CUTEst.jl -- Part II

---

Artifacts.toml
src/sifdecoder.jl

close #337 
We fixed the last bugs in the SIF files and the decoder such that all problems can be decoded in `single`, `double` or `quadruple` precision with Nick.
A new release of `SIFDecode_jll.jl` is also needed but it will be in another PR.

Update the sifcollection in Artifacts.toml

---

Project.toml

This version allows to decode all SIF problems in single, double and quadruple precision.

Use the version 2.6.0 of SIFDecode_jll.jl

---

gen/wrapper.jl
src/core_interface.jl
src/julia_interface.jl
src/libcutest.jl
src/model.jl
test/test_core.jl

- use the Julia wrappers in `libcutest.jl` to easily update `CUTEst_jll.jl` in the future and support various precision.
- Update functions in `core_interface.jl` to use the C version `*_cint_*` instead of the F77 version because the type `logical` can have different sizes depending on the Fortran compiler.
The following routines are concerned:
- cutest_cint_csetup
- cutest_cint_cnoobj
- cutest_cint_uofg
- cutest_cint_ueh
- cutest_cint_ugreh
- cutest_cint_uhprod
- cutest_cint_ushprod
- cutest_cint_cofg
- cutest_cint_cofsg
- cutest_cint_ccfg
- cutest_cint_clfg
- cutest_cint_cgr
- cutest_cint_csgr
- cutest_cint_csgrp
- cutest_cint_csjp
- cutest_cint_ccfsg
- cutest_cint_ccifg
- cutest_cint_ccifsg
- cutest_cint_cgrdh
- cutest_cint_csgrsh
- cutest_cint_csgrshp
- cutest_cint_csgreh
- …

Use the Julia wrappers in CUTEst.jl -- Part III

---

.github/workflows/ci.yml
gen/wrapper.jl
src/CUTEst.jl
src/core_interface.jl
src/julia_interface.jl
src/libcutest.jl
src/model.jl
src/sifdecoder.jl
test/runtests.jl
test/test_core.jl

:crossed_fingers: 
Should be merged after #344 and #349 if it works one day...

[CUTEst.jl] Support Windows

---

docs/src/core.md
gen/wrapper.jl
src/CUTEst.jl
src/core_interface.jl
src/libcutest.jl
src/model.jl
src/sifdecoder.jl

Should be merged after https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/344, https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/349, https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/350, https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/351 and #352

Prepare CUTEst.jl for single and quadruple precision

---

src/julia_interface.jl
src/model.jl

Remove a few allocations

---

Project.toml
gen/Project.toml
gen/wrapper.jl
test/coverage.jl

- It's a big upgrade for `CUTEst_jll.jl`; the previous version was a few years old...
- CUTEst deallocates memory that it should not free... (the issue is between releases `v2.0.7` and `v2.0.27`)

Use CUTEst_jll.jl v2.2.2

---

Project.toml
src/CUTEst.jl
src/core_interface.jl
src/libcutest.jl
src/model.jl
test/runtests.jl
test/test_core.jl
test/test_julia.jl

@oscardssmith @RalphAS 
Do you know what is the best way to provide a `Vector` of a `Ref` of `Float128` to a Fortran routine?
The Fortran routines probably needs a Vector of `Cfloat128`, am I right?

Interface routines for quadruple precision

---

README.md
gen/wrapper.jl
src/CUTEst.jl
src/core_interface.jl
src/julia_interface.jl
src/libcutest.jl
src/model.jl
src/sifdecoder.jl
test/coverage.jl
test/runtests.jl
test/test_core.jl

Each shared library dedicated to a SIF problem in a given precision is no longer linked to the same `libcutest_$precision.$dlext`. This previously caused issues when attempting to use multiple `CUTEstModel` instances for the same precision simultaneously. 
By using static libraries instead, multiple problems can now be used simultaneously without conflict, as each library is independent from the others due to static linking.
I have modified the wrapper generator to add a `libsif` argument, which is of type `Ptr{Cvoid}`, returned by `Libdl.dlopen`. Each `CUTEstModel` now has a `libsif` field.
Users no longer need to manually call `finalizer(nlp)`; the garbage collector will handle it automatically. The only scenario where it might be necessary is if the user recreates a model with the same …

Multiple instances of CUTEstModel can now coexist

---

src/CUTEst.jl
src/julia_interface.jl
src/model.jl

Remove some allocations in CUTEst.jl

---

src/model.jl
src/sifdecoder.jl
test/runtests.jl

close #446 
Feature relevant for `GALAHAD.jl` where we don't want `libcutest.a` embedded in the shared library of the SIF problem.

Add an option to compile standalone shared libraries for SIF problems

---

src/CUTEst.jl
src/julia_interface.jl
src/model.jl
test/runtests.jl
test/test_allocations.jl

close #302 
I also added allocations tests in single / double / quadruple precision.

Remove all allocations

---

src/sifdecoder.jl

@jfowkes @nimgould
The new release of SIFDecode broke `CUTEst.jl` because `STOP 0` is written in `stderr` and not `stdout`.
I was checking that `stderr` was empty before.
This PR quickly fixes the issue.
It could be relevant for you to know that if you want to use it in the Python interface.

Update CUTEst.jl for SIFDecode 3.1.0
