JuliaSmoothOptimizers/CUTEst.jl

- .travis.yml
[Why sudo: required](http://blog.travis-ci.com/2015-03-31-docker-default-on-the-way/)
> Add sudo: required, as instructed on travis

- interface_script/build_interface.py
- interface_script/generate_specialized_test.py
- src/CUTEst.jl
- src/core_interface.jl
- src/julia_interface.jl
- src/specialized_interface.jl
- test/runtests.jl
- test/runtests_unc.jl
- test/test_core.jl
- test/test_specialized.jl
This refactor #26 squashing similar commits.
The work could be divided into three parts:
- Refactoring
- Creating the specialized interface
- Creating the tests for the specialized interface
> Refactor script and implement the specialized interface

- .travis.yml
- src/CUTEst.jl
`require` is deprecated on 0.4
> Require is deprecated on 0.4

- interface_script/build_interface.py
- src/specialized_interface.jl
- test/test_specialized.jl
> Remove useless inplace and wrong NLP interfaces

- src/CUTEst.jl
Travis broke, but my computer didn't.
> Fix problem with nnet

- interface_script/build_interface.py
- interface_script/generate_specialized_test.py
- src/CUTEst.jl
- src/core_interface.jl
- src/documentation.jl
- src/julia_interface.jl
- src/specialized_interface.jl
- test/test_core.jl
- test/test_julia.jl
- test/test_specialized.jl
> Remove `@eval` from everywhere

- test/test_core.jl
- test/test_julia.jl
- test/test_specialized.jl
Shouldn't be a problem anymore, and lead to faster builds.
> Decrease stress

- src/CUTEst.jl
- src/mpb_interface.jl
- test/REQUIRE
- test/runtests.jl
- test/test_mpb.jl
> MathProgBase interface

- src/CUTEst.jl
- src/julia_interface.jl
- src/mpb_interface.jl
- test/runtests.jl
- test/test_julia.jl
- test/test_mpb.jl
Change 1e20 to Inf and -1e20 to -Inf.
Change hess related functions to use keyword y.
> Changes for consistency on NLPModels

- docs/src/core.md
- interface_script/build_interface.py
- interface_script/generate_specialized_test.py
- src/specialized_interface.jl
- test/runtests.jl
- test/test_specialized.jl
> Simplify specialized interface

- src/CUTEst.jl
- test/consistency.jl
- test/runtests.jl
- test/test_mpb.jl
> Add cutest_finalize as a finalizer

- interface_script/build_interface.py
- src/CUTEst.jl
- src/specialized_interface.jl
- test/runtests.jl
- test/test_specialized_manual.jl
Increasing coverage.
Also, found an error with the specialized `csetup` too. Decided on using `logical->Cint` for this function.
> Test non-NLP decoding, opening, setup and closing

- docs/make.jl
> Change release to 0.5 on docs

- interface_script/generate_specialized_test.py
- src/CUTEst.jl
- src/classification.jl
- test/test_specialized.jl
Despite the discussion on #97 , this is an error, and I'm just fixing it. Questions there still apply, but people using it in the meantime shouldn't be as confused as before.
> Change cutest_finalize to finalize on the last wrong places

- .travis.yml
- deps/build.jl
Tried to install the dependencies using BinDeps, but failed miserably.
This transfer the burden to [linux-cutest](https://github.com/abelsiqueira/linux-cutest).
> linux-cutest now install linux dependencies (at least on Travis)

- .travis.yml
- REQUIRE
- docs/make.jl
- src/julia_interface.jl
Depends on https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/75
> Update objcons and objgrad to work with NLPModels

- src/core_interface.jl
- src/specialized_interface.jl
- test/consistency.jl
- test/coverage.jl
- test/runtests.jl
- test/test_specialized.jl
Due to #113, I removed `HS10` from the tests.
> Add many tests for specialized functions

- deps/build.jl
- src/CUTEst.jl
- test/test_specialized_manual.jl
Remove unnecessary check for package Homebrew.
Download tagged version of linux-cutest.
Change ENV variable 'CUTEst problems' to 'cutest-problems'.
@tkelman
> Tony Kelman's review

- .travis.yml
- REQUIRE
- src/CUTEst.jl
- src/julia_interface.jl
- src/specialized_interface.jl
- test/REQUIRE
- test/runtests.jl
- test/test_core.jl
- test/test_julia.jl
- test/test_select.jl
- test/test_specialized.jl
Needs [NLPModels update](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/issues/84).
> Fix for 0.6

- deps/build.jl
> Change build to update CUTEst on linux

- src/core_interface.jl
> Disclaimer on dimensions of vectors in {u,c}shprod

- .travis.yml
- deps/build.jl
- src/CUTEst.jl
Related to https://github.com/abelsiqueira/linux-cutest/issues/11
> Update installation to keep a link to libgfortran.so on deps/

- README.md
- src/CUTEst.jl
This allows different `CUTEstModels` to be run in parallel.
I don't know that `AUTOMAT.d` does, but I'm storing one for each model in case someone knows what to do with them.
Fixes https://github.com/JuliaSmoothOptimizers/CUTEst.jl/issues/51#issuecomment-354757852
> Make OUTSDIF.d problem dependent

- deps/build.jl
- src/classf.json
> Update linux-cutest version to 0.3.3 because of mastsif-mirror v0.4

- .zenodo.json
@dpo Do you have experience with Zenodo? Are we supposed to update the version every time before a new release?
> Update Zenodo to v0.3.2

- src/CUTEst.jl
See https://github.com/abelsiqueira/linux-cutest/issues/14#issuecomment-380606665.
> fix location of libgfortran on linux

- deps/build.jl
- fully qualify CUTEst tap
- only install GSL if another installation is not found
> fix install of GSL

- .travis.yml
- REQUIRE
- deps/build.jl
- src/CUTEst.jl
- src/classification.jl
- src/core_interface.jl
- src/julia_interface.jl
- test/consistency.jl
- test/coverage.jl
- test/runtests.jl
- test/test_core.jl
- test/test_select.jl
Needs https://github.com/JuliaLang/METADATA.jl/pull/18614
> Drop 0.6 and update to Julia 1.0

- src/CUTEst.jl
> use problem basename instead of full path

- .travis.yml
- REQUIRE
- src/julia_interface.jl
- test/consistency.jl
- test/runtests.jl
- test/test_view_subarray.jl
Uses `test_view_array` from `NLPModels.jl`.
> Allow AbstractVector in interface

- docs/make.jl
- docs/src/api.md
- src/julia_interface.jl
requires https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/188
> in-place structure methods

- docs/make.jl
- docs/src/api.md
- src/julia_interface.jl
The docstrings were duplicated.
> Remove NLPModels docstrings and add link to API in the docs

- src/julia_interface.jl
needs https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/188 and #185.
> Simplify methods by falling back on defaults

- src/CUTEst.jl
- src/julia_interface.jl
> remove trailing semicolons

- src/julia_interface.jl
> assign structure arrays of appropriate size

- Project.toml
Can't `Pkg.build("CUTEst")` without it
> Add BinDeps to deps

- src/CUTEst.jl
After a few months, they really add up.
> Remove more temporary files

- Project.toml
First version supporting NLPModels 0.11
> Version 0.9.0

- README.md
> remove pkgevaluator badges

- Project.toml
- src/CUTEst.jl
> fix path to helper_functions

- src/CUTEst.jl
- test/runtests.jl
> Fix decoding issue

- src/CUTEst.jl
`global const` -> `const` in one line.
> Fix formatter

- Project.toml
- docs/Project.toml
- docs/src/tutorial.md
- test/test_core.jl
- test/test_julia.jl
No src files were changed, only the tests, so the version only has a minor bump
> Bump to NLPModels 0.16 and 0.17 and update Version to 0.12.1

- test/runtests.jl
https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/pull/39
> Add hs13 from NLPModelsTest

- test/nlpmodelstest.jl
Following https://github.com/JuliaSmoothOptimizers/NLPModelsTest.jl/pull/58
> add `linear_api` tests

- docs/Project.toml
- docs/make.jl
- docs/src/reference.md
- docs/src/tutorial.md
- src/classification.jl
> Fix the documentation

- docs/src/index.md
Added high-level steps and tips to run Julia and CUTEst from Windows Subsystem for Linux.
> Update index.md to explain how to use CUTEst from Windows

- docs/src/index.md
- src/CUTEst.jl
> Document parameters passed to sifdecoder

- CITATION.bib
- CITATION.cff
@software{Orban_CUTEst_jl_Julia_s_CUTEst_2023,
author = {Orban, Dominique and Soares Siqueira, Abel and contributors},
month = mar,
title = {{CUTEst.jl: Julia's CUTEst interface}},
url = {https://github.com/JuliaSmoothOptimizers/CUTEst.jl},
version = {0.13.2},
year = {2023}
}
> Use cff instead of bib

- Project.toml
- src/CUTEst.jl
> Use CUTEst_jll.jl v2.0.7 with Windows support

- src/julia_interface.jl
- src/model.jl
- test/runtests.jl
- test/test_julia.jl
close #329 
Should be merged after #344, #349 and #350
> All sparsity patterns are computed when we create a CUTEstModel

- src/julia_interface.jl
close #317 
Should be merged after https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/344, https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/349, https://github.com/JuliaSmoothOptimizers/CUTEst.jl/pull/350 and #351
> Interface jth_hess_coord!

- Artifacts.toml
- src/sifdecoder.jl
> Use the latest release of sifcollection

- src/CUTEst.jl
- src/sifdecoder.jl
- test/multiple_precision.jl
- test/runtests.jl
> Add the tests of Abel for single precision

- src/model.jl
- test/coverage.jl
- test/multiple_precision.jl
- test/runtests.jl
- test/test_core.jl
- test/test_julia.jl
Thanks to the release `v2.2.2`, we can support single precision.
> Support CUTEstModel in single precision

- src/sifdecoder.jl
> remove run and mv for OUTSDIF.d

- src/julia_interface.jl
- src/model.jl
Should be merged after #375 
Suggested by Nick Gould.
> Use ccfsg for cons!

- src/julia_interface.jl
- test/multiple_precision.jl
- test/nlpmodelstest.jl
- test/runtests.jl
> Add unit tests for jth_hess_coord

- Project.toml
> Release 1.0.0

- src/model.jl
- test/runtests.jl
Found in https://github.com/libprima/PRIMA.jl/pull/31
> Fix type instability in CUTEst.jl due to support for single and quadruple precision

- .breakage/Project.toml
- .breakage/get_jso_users.jl
- .github/workflows/Breakage.yml
- copier-answers.jso.yml
Automated update using JSOBestieTemplate
> Update with JSOBestieTemplate for CUTEst

- Artifacts.toml
> Update the sifcollection in Artifacts.toml

- src/CUTEst.jl
> Display a warning if Julia and gfortran are compiled for different architectures

- .github/workflows/ci.yml
- test/multiple_precision.jl
- test/runtests.jl
Since last week we can do CI with the platform ARM linux.
> [CI] Test CUTEst.jl on Linux ARM

- src/classification.jl
- test/runtests.jl
> Remove select

- LICENSE.md
> Replace the license LGPL by a MPL 2.0
